{$IFDEF VER210}
  {$DEFINE Delphi2010orHigher}
{$ENDIF}
{$IFDEF VER220}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
{$ENDIF}
{$IFDEF VER230}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER240}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER250}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER260}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER270}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER280}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER290}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
{$ENDIF}
{$IFDEF VER300}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
  {$DEFINE Delphi10Seattle}
{$ENDIF}
{$IFDEF VER310}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
  {$DEFINE Delphi101Berlin}
{$ENDIF}
{$IFDEF VER320}
  {$DEFINE Delphi2010orHigher}
  {$DEFINE DelphiXEorHigher}
  {$DEFINE DelphiXE2orHigher}
  {$DEFINE Delphi102Tokyo}
{$ENDIF}

